local opt = vim.opt

opt.backup = false
opt.clipboard = "unnamedplus"
opt.completeopt = { "menuone", "noselect" }
opt.conceallevel = 0
opt.fileencoding = "utf-8"
opt.hlsearch = true
opt.ignorecase = true
opt.mouse = "a"
opt.mousemoveevent = true
opt.pumheight = 10
opt.showmode = false
opt.showtabline = 2
opt.laststatus = 2
opt.smartcase = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.termguicolors = true
opt.timeoutlen = 1000
opt.undofile = true
opt.updatetime = 300
opt.writebackup = false
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.cursorline = true
opt.number = true
opt.relativenumber = true
opt.numberwidth = 4
opt.signcolumn = "yes"
opt.wrap = true
opt.scrolloff = 5
opt.guifont = "Hack Nerd Font Mono:h14"
opt.list = true
opt.lcs = [[tab:  ,trail:▫]]
opt.lbr = true
opt.guicursor =
[[n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor,sm:block-blinkwait175-blinkoff150-blinkon175]]
